#include "builtins/env.h"
#include "parser/automata/nfa.h"
#include "tokenizer/tokenizer.h"
#include "ast/ast.h"
#include "builtins/builtins.h"
#include "signals/signal_modes.h"
#include <readline/readline.h>
#include <readline/history.h>

void	main_loop(void);

static void	increment_shlvl(void)
{
	t_env	*env;
	int		next_shlvl;

	env = find_env_var("SHLVL");
	if (env == NULL)
	{
		append_env_list("SHLVL", ft_strdup("1"));
		return ;
	}
	next_shlvl = ft_atoi(env->val) + 1;
	free(env->val);
	env->val = ft_itoa(next_shlvl);
}

static int	print_flags_singleton(int *new_val)
{
	static int	saved_val;

	if (new_val != NULL)
		saved_val = *new_val;
	return (saved_val);
}

int	get_printing_flags(void)
{
	return (print_flags_singleton(NULL));
}

int	set_printing_flags(int new_val)
{
	return (print_flags_singleton(&new_val));
}

void	print_help_message(void)
{
	write(1, "\nWelcome to our little shell!\n\n", 30);
	write(1, "When launching minishell, you can\n", 34);
	write(1, "provide either \"--help\" or \"--show\" flags.\n", 44);
	write(1, "The \"", 5);
	write(1, "\033[0;31m", 7);
	write(1, "--show", 6);
	write(1, "\033[0;37m", 7);
	write(1, "\" flag requires one additional argument:\n", 41);
	write(1, "\t1. \"", 6);
	write(1, "\033[0;31m", 7);
	write(1, "ast", 3);
	write(1, "\033[0;37m", 7);
	write(1, "\" to print the abstract syntax tree generated by our parser,\n", 61);
	write(1, "\t2. \"", 5);
	write(1, "\033[0;31m", 7);
	write(1, "tokens", 6);
	write(1, "\033[0;37m", 7);
	write(1, "\" to print list of tokens used to build the tree.\n", 50);
	write(1, "\t3. \"", 5);
	write(1, "\033[0;31m", 7);
	write(1, "all", 3);
	write(1, "\033[0;37m", 7);
	write(1, "\" to show both.\n", 16);
	write(1, "\nHave fun !!!\n\n", 15);
	exit(1);
}

int	handle_argv(int argc, char **argv)
{
	if (argc == 1)
		return (0);;
	if (argc > 3)
		print_help_message();
	if (ft_strcmp(argv[1], "--help") == 0)
		print_help_message();
	if (ft_strcmp(argv[1], "--show") == 0)
	{
		if (argc != 3)
			print_help_message();
		if (ft_strcmp(argv[2], "ast") == 0)
			return (set_printing_flags(1));
		else if (ft_strcmp(argv[2], "tokens") == 0)
			return (set_printing_flags(2));
		else if (ft_strcmp(argv[2], "all") == 0)
			return (set_printing_flags(3));
	}
	print_help_message();
	return (1);
}

int	main(int argc, char *argv[], char *envp[])
{
	handle_argv(argc, argv);
	create_env_list(envp);
	increment_shlvl();
	main_loop();
}
