#include <unistd.h>
#include <stdlib.h>

void	print_help_message(void)
{
	write(1, "\nWelcome to our little shell!\n\n", 30);
	write(1, "When launching minishell, you can\n", 34);
	write(1, "provide either \"--help\" or \"--show\" flags.\n", 44);
	write(1, "The \"", 5);
	write(1, "\033[0;31m", 7);
	write(1, "--show", 6);
	write(1, "\033[0;37m", 7);
	write(1, "\" flag requires one additional argument:\n", 41);
	write(1, "\t1. \"", 6);
	write(1, "\033[0;31m", 7);
	write(1, "ast", 3);
	write(1, "\033[0;37m", 7);
	write(1, "\" to print the ast generated by our parser,\n", 61);
	write(1, "\t2. \"", 5);
	write(1, "\033[0;31m", 7);
	write(1, "tokens", 6);
	write(1, "\033[0;37m", 7);
	write(1, "\" to print list of tokens used to build the tree.\n", 50);
	write(1, "\t3. \"", 5);
	write(1, "\033[0;31m", 7);
	write(1, "all", 3);
	write(1, "\033[0;37m", 7);
	write(1, "\" to show both.\n", 16);
	write(1, "\nHave fun !!!\n\n", 15);
	exit(1);
}
